/**
 * Enumeration of different types of chunks that can exist in a task's scratchpad.
 */
export enum ChunkType {
    /** Input provided to an agent or task */
    Input = 'input',
    /** Output generated by a language model */
    LlmOutput = 'llmOutput',
    /** Output from tool execution */
    ToolOutput = 'toolOutput',
    /** Output from agent execution */
    AgentOutput = 'agentOutput',
    /** Error information or messages */
    Error = 'error',
    /** Arbitrary data storage */
    Data = 'data'
}

/**
 * Enumeration of different types of tasks that can be executed.
 */
export enum TaskType {
    /** Standard task for agent execution */
    Regular = 'regular',
    /** Task specifically for evaluator execution */
    Evaluator = 'evaluator'
}

/**
 * Represents a piece of data or message in a task's scratchpad.
 * Chunks are the basic units of communication and data storage in the agent system.
 */
export interface Chunk {
    /** The type of this chunk, determining how it's processed */
    type: ChunkType;
    /** The actual content of the chunk as a string */
    content: string;
    /** Whether this chunk has been processed by the system */
    processed: boolean;
    /** Optional ID linking this chunk to a specific message */
    messageId?: string;
    /** Optional metadata annotations added by evaluators */
    annotations?: Record<string, any>;
}

/**
 * Represents a unit of work to be executed by an agent.
 * Tasks contain input data, maintain a scratchpad of chunks, and track execution state.
 */
export interface Task {
    /** Unique identifier for this task */
    id: string;
    /** Name of the agent responsible for executing this task */
    agent_name: string;
    /** Input data provided to the agent */
    input: any;
    /** ID of the parent task, null for root tasks */
    parent_task_id: string | null;
    /** Array of chunks containing the task's data and conversation history */
    scratchpad: Chunk[];
    /** Number of times this task has been retried due to errors */
    retryCount: number;
    /** Number of times this task has been executed */
    executionCount?: number;
    /** Optional type classification for the task */
    taskType?: TaskType;
    /** Optional callback function called when the task completes */
    onComplete?: (result: string | {content: string, annotation?: any, annotations?: Record<string, any>}) => void;
}